from ui.themeengine.localization.helpers import MESSAGES
from ui.themeengine.localization.locale_msgs import LocaleMsgs

MESSAGES.append(
    # SPANISH translation
    LocaleMsgs(
        "es_mx",
        # Botones principales y acciones básicas
        ("OK", "Aceptar"),
        ("Ok", "Aceptar"),
        ("Cancel", "Cancelar"),
        ("Yes", "Sí"),
        ("No", "No"),
        ("Submit", "Enviar"),
        ("Retry", "Reintentar"),
        ("Ignore", "Ignorar"),
        ("Abort", "Cancelar"),
        ("&OK", "&Aceptar"),
        ("&Cancel", "&Cancelar"),
        ("&Yes", "&Sí"),
        ("&No", "&No"),
        ("&Retry", "&Reintentar"),
        ("&Abort", "&Cancelar"),
        ("&Ignore", "&Ignorar"),
        ("&Apply", "&Aplicar"),
        ("ok", "aceptar"),
        ("yes", "sí"),
        ("no", "no"),
        ("abort", "cancelar"),
        ("ignore", "ignorar"),
        ("retry", "reintentar"),
# Navegación
        ("Next", "Siguiente"),
        ("Previous", "Anterior"),
        ("Prev", "Anterior"),
        ("Continue", "Continuar"),
        ("Open", "Abrir"),
        ("Close", "Cerrar"),
        ("Exit", "Salir"),
        ("E&xit", "S&alir"),
        ("Quit", "Salir"),
        ("&Quit", "&Salir"),
        ("&Open", "&Abrir"),
        ("Skip Messages", "Saltar mensajes"),
# Acciones de edición
        ("Add", "Agregar"),
        ("Remove", "Quitar"),
        ("Delete", "Eliminar"),
        ("Edit", "Editar"),
        ("&Edit", "&Editar"),
        ("Copy", "Copiar"),
        ("&Copy", "&Copiar"),
        ("Cut", "Cortar"),
        ("Cu&t", "Cor&tar"),
        ("Paste", "Pegar"),
        ("P&aste", "P&egar"),
        ("Save", "Guardar"),
        ("&Save", "&Guardar"),
        ("Clear", "Limpiar"),
        ("Cl&ear", "Limp&iar"),
        ("&Clear Console", "&Limpiar consola"),
        ("Select", "Seleccionar"),
        ("&Selection:", "&Selección:"),
        ("Hide", "Ocultar"),
        ("&Hide Console", "&Ocultar consola"),
        ("Show", "Mostrar"),
        ("Filter", "Filtrar"),
        ("&Filter", "&Filtrar"),
        ("Fil& :", "Filt&rar:"),
        ("Search", "Buscar"),
        ("Sort", "Ordenar"),
        ("Export", "Exportar"),
        ("&Delete", "&Eliminar"),

# Días de la semana
        ("Mo", "Lu"),
        ("Tu", "Ma"),
        ("We", "Mi"),
        ("Th", "Ju"),
        ("Fr", "Vi"),
        ("Sa", "Sá"),
        ("Su", "Do"),

# Operaciones de tablas y listas
        ("Move", "Mover"),
        ("⎌", "↺"),
        ("Reset table", "Reiniciar tabla"),
        ("Move up", "Mover arriba"),
        ("Move down", "Mover abajo"),
        ("Move to top", "Mover al inicio"),
        ("Move to bottom", "Mover al final"),
        ("Move to left", "Mover a la izquierda"),
        ("Move to right", "Mover a la derecha"),
        ("Move to first", "Mover al primero"),
        ("Move to last", "Mover al último"),
        ("Sort Ascending", "Ordenar ascendente"),
        ("Sort Descending", "Ordenar descendente"),
        ("Clear filters", "Limpiar filtros"),
        ("Delete selected rows", "Eliminar filas seleccionadas"),
        ("Hide select rows", "Ocultar filas seleccionadas"),
        ("Show only select rows", "Mostrar solo filas seleccionadas"),
        ("Export all records", "Exportar todos los registros"),
        ("Export current page", "Exportar página actual"),
        ("Export current selection", "Exportar selección actual"),
        ("Export records in filter", "Exportar registros filtrados"),
        ("Filter by cell's value", "Filtrar por valor de celda"),

# Estructura de documentos y archivos
        ("Save As", "Guardar como"),
        ("Save To Log", "Guardar en registro"),
        ("Select Log File", "Seleccionar archivo de registro"),
        ("Select a file to source", "Seleccionar un archivo de origen"),
        ("&Source...", "&Origen..."),
        ("All Files", "Todos los archivos"),
        ("Text Files", "Archivos de texto"),
        ("Log Files", "Archivos de registro"),
        ("File", "Archivo"),
        ("&File", "&Archivo"),
        ("Files", "Archivos"),
        ("Fi&les:", "Ar&chivos:"),
        ("File &name:", "Nombre de &archivo:"),
        ("File &names:", "Nombres de &archivos:"),
        ("Files of &type:", "Archivos de &tipo:"),
        ("Directory", "Directorio"),
        ("&Directory:", "&Directorio:"),
        ("Choose Directory", "Elegir directorio"),
        ("extension", "extensión"),
        ("extensions", "extensiones"),
        ("Open Multiple Files", "Abrir múltiples archivos"),
        ("Replace existing file?", "¿Reemplazar archivo existente?"),
        ('Cannot change to the directory %1\\$s.\\nPermission denied.', 'No se puede cambiar al directorio %1\\$s.\\nPermiso denegado.'),
        ('Directory %1\\$s does not exist.', 'El directorio %1\\$s no existe.'),
        ('File %1\\$s already exists.\\nDo you want to overwrite it?', 'El archivo %1\\$s ya existe.\\n¿Desea sobrescribirlo?'),
        ('File %1\\$s already exists.\\n\\n', 'El archivo %1\\$s ya existe.\\n\\n'),
        ('File %1\\$s does not exist.', 'El archivo %1\\$s no existe.'),
        ('Invalid file name %1\\$s.', 'Nombre de archivo inválido %1\\$s.'),
        ("Page", "Página"),
        ("of", "de"),
        ("Show &Hidden Directories", "Mostrar directorios &ocultos"),
        ("Show &Hidden Files and Directories", "Mostrar archivos y directorios &ocultos"),

# Alineación y disposición
        ("Align", "Alinear"),
        ("Align left", "Alinear a la izquierda"),
        ("Align center", "Alinear al centro"),
        ("Align right", "Alinear a la derecha"),
        ("Columns", "Columnas"),
        ("Hide column", "Ocultar columna"),
        ("Delete column", "Eliminar columna"),
        ("Show All", "Mostrar todo"),
        ("Details >>", "Detalles >>"),

# Colores
        ("Red", "Rojo"),
        ("Green", "Verde"),
        ("Blue", "Azul"),
        ("Color", "Color"),
        ("Color Chooser", "Selector de color"),
        ("color dropper", "Cuentagotas de color"),
        ("Hue", "Matiz"),
        ("Sat", "Saturación"),
        ("Lum", "Luminosidad"),
        ("Hex", "Hexadecimal"),
        ("&Red", "&Rojo"),
        ("&Green", "&Verde"),
        ("&Blue", "&Azul"),
        ("red", "rojo"),
        ("green", "verde"),
        ("blue", "azul"),

# Atributos de fuentes
        ("Font", "Fuente"),
        ("Font Selector", "Selector de fuentes"),
        ("&Font:", "&Fuente:"),
        ("Font st&yle:", "Est&ilo de fuente:"),
        ("Family", "Familia"),
        ("Weight", "Peso"),
        ("Slant", "Inclinación"),
        ("Size", "Tamaño"),
        ("&Size:", "&Tamaño:"),
        ("Effects", "Efectos"),
        ("Preview", "Vista previa"),
        ("Sample", "Ejemplo"),
        ("normal", "normal"),
        ("bold", "negrita"),
        ("Bold", "Negrita"),
        ("Bold Italic", "Negrita cursiva"),
        ("negrito", "negrita"),
        ("roman", "romano"),
        ("italic", "cursiva"),
        ("Italic", "Cursiva"),
        ("underline", "subrayado"),
        ("&Underline", "&Subrayado"),
        ("overstrike", "tachado"),
        ("Stri&keout", "Ta&chado"),
        ("Regular", "Regular"),

# Estados y temas visuales
        ("Advanced", "Avanzado"),
        ("Standard", "Estándar"),
        ("Current", "Actual"),
        ("New", "Nuevo"),
        ("Themed", "Tema"),
        ("Options", "Opciones"),

# Mensajes de error y validación
        ("Should be of data type", "Debe ser del tipo de datos"),
        ("Should be a of data type", "Debe ser del tipo de datos"),
        ("Invalid data type", "Tipo de datos inválido"),
        ("Number cannot be greater than", "El número no puede ser mayor que"),
        ("Out of range", "Fuera de rango"),
        ("Error", "Error"),
        ("Error: %1\\$s", "Error: %1\\$s"),
        ("Application Error", "Error de aplicación"),

# Impresión
        ("Print", "Imprimir"),
        ("Printer", "Impresora"),
        ("Copies", "Copias"),
        ("Paper", "Papel"),
        ("Scale", "Escala"),
        ("Orientation", "Orientación"),
        ("Portrait", "Vertical"),
        ("Landscape", "Horizontal"),
        ("Output", "Salida"),
        ("Grayscale", "Escala de grises"),
        ("RGB", "RGB"),
        ("Letter ", "Carta "),
        ("Legal ", "Oficio "),
        ("A4", "A4"),

# Elementos técnicos específicos
        ("Console", "Consola"),
        ("Tcl Scripts", "Scripts Tcl"),
        ("Tcl for Windows", "Tcl para Windows"),
        ("&Help", "&Ayuda"),
        ("&About...", "&Acerca de..."),

# Frases de ejemplo
        ("The quick brown fox jumps over the lazy dog.", "El veloz zorro marrón salta sobre el perro perezoso."),
        ("Hi", "Hola"),
    )
)